return {
  "akinsho/nvim-bufferline.lua",
  event = "BufReadPost",
  keys = {
    { "<Tab>", "<Cmd>BufferLineCycleNext<CR>", desc = "Next buffer" },
    { "<S-Tab>", "<Cmd>BufferLineCyclePrev<CR>", desc = "Prev buffer" },
    { "<m-p>", "<Cmd>BufferLineTogglePin<CR>", desc = "Pin buffer" },
    { "db", "<Cmd>BufferLinePickClose<CR>", desc = "Pick close buffer" },
    { "dlb", "<Cmd>BufferLineCloseLeft<CR>", desc = "Close left buffers" },
    { "drb", "<Cmd>BufferLineCloseRight<CR>", desc = "Close right buffers" },
    { "<leader>1", "<Cmd>BufferLineGoToBuffer 1<CR>", desc = "Buffer 1" },
    { "<leader>2", "<Cmd>BufferLineGoToBuffer 2<CR>", desc = "Buffer 2" },
    { "<leader>3", "<Cmd>BufferLineGoToBuffer 3<CR>", desc = "Buffer 3" },
    { "<leader>4", "<Cmd>BufferLineGoToBuffer 4<CR>", desc = "Buffer 4" },
    { "<leader>5", "<Cmd>BufferLineGoToBuffer 5<CR>", desc = "Buffer 5" },
    { "<leader>6", "<Cmd>BufferLineGoToBuffer 6<CR>", desc = "Buffer 6" },
    { "<leader>7", "<Cmd>BufferLineGoToBuffer 7<CR>", desc = "Buffer 7" },
    { "<leader>8", "<Cmd>BufferLineGoToBuffer 8<CR>", desc = "Buffer 8" },
    { "<leader>9", "<Cmd>BufferLineGoToBuffer 9<CR>", desc = "Buffer 9" },
    { "<leader>0", "<Cmd>BufferLineGoToBuffer -1<CR>", desc = "Last buffer" },
  },
  opts = {
    options = {
      separator_style = "thin",
      numbers = "ordinal",
      left_mouse_command = "buffer %d",
      middle_mouse_command = "Bdelete! %d",
      indicator = { icon = "▎", style = "icon" },
      diagnostics_indicator = function(count)
        return count > 9 and "9+" or tostring(count)
      end,
      modified_icon = "●",
      left_trunc_marker = "",
      right_trunc_marker = "",
      max_name_length = 25,
      max_prefix_length = 25,
      tab_size = 18,
      diagnostics = "nvim_lsp",
      diagnostics_update_in_insert = false,
      offsets = { { filetype = "neo-tree", text = "File System", text_align = "center" } },
      show_buffer_icons = true,
      show_buffer_close_icons = false,
      show_close_icon = false,
      show_tab_indicators = false,
      persist_buffer_sort = true,
      enforce_regular_tabs = true,
      always_show_bufferline = true,
    },
    highlights = {
      buffer_selected = { fg = "#fdf6e3", bold = true, italic = false },
      fill = { bg = "#073642" },
    },
  },
}
