return {
  "akinsho/toggleterm.nvim",
  keys = { { "<m-->", desc = "Toggle terminal" } },
  cmd = "ToggleTerm",
  opts = {
    size = 30,
    open_mapping = [[<m-->]],
    hide_numbers = true,
    highlights = { NormalFloat = { link = "Normal" } },
    shade_terminals = true,
    shading_factor = 4,
    start_in_insert = true,
    insert_mappings = true,
    terminal_mappings = true,
    persist_size = true,
    direction = "float",
    close_on_exit = true,
    shell = vim.o.shell,
    float_opts = { border = "none", winblend = 0 },
  },
}
