return {
  "nvimdev/lspsaga.nvim",
  event = "LspAttach",
  keys = {
    { "K", "<cmd>Lspsaga hover_doc<CR>", desc = "Hover doc" },
    { "gf", "<cmd>Lspsaga finder<CR>", desc = "LSP finder" },
    { "gp", "<cmd>Lspsaga peek_definition<CR>", desc = "Peek definition" },
    { "gr", "<cmd>Lspsaga rename<CR>", desc = "Rename" },
    { "gd", "<cmd>Lspsaga goto_definition<CR>", desc = "Goto definition" },
    { "<leader>o", "<cmd>Lspsaga outline<CR>", desc = "Outline" },
    { "<leader>ci", "<cmd>Lspsaga incoming_calls<CR>", desc = "Incoming calls" },
    { "<leader>co", "<cmd>Lspsaga outgoing_calls<CR>", desc = "Outgoing calls" },
  },
  opts = {
    rename = { quit = "<C-c>", exec = "<CR>", mark = "x", confirm = "<CR>", in_select = true },
    outline = {
      win_position = "right",
      win_width = 30,
      preview_width = 0.5,
      show_detail = true,
      auto_preview = true,
      auto_refresh = true,
      auto_close = true,
      keys = { expand_or_jump = "o", quit = "q" },
    },
    ui = {
      title = true,
      border = "single",
      winblend = 0,
      expand = "",
      collapse = "",
      code_action = "💡",
      incoming = " ",
      outgoing = " ",
      hover = " ",
    },
  },
}
